fix: value is required for `page-fallback`
error: a value is required for '--page-fallback <PAGE_FALLBACK>' but none was supplied

now is ok to pass an empty --page-fallback argument or empty SERVER_FALLBACK_PAGE

log example when --page-fallback or its env is empty:

2023-06-08T20:34:13.806318Z  INFO static_web_server::logger: logging level: trace
2023-06-08T20:34:13.806540Z DEBUG static_web_server::server: initializing tokio runtime with multi thread scheduler self.worker_threads=8
2023-06-08T20:34:13.808290Z TRACE static_web_server::server: starting web server
2023-06-08T20:34:13.808557Z  INFO static_web_server::server: server bound to tcp socket [::]:8787
2023-06-08T20:34:13.808795Z  INFO static_web_server::server: fallback page: enabled=false, value=""